# Generated by Django 4.1.1 on 2022-11-17 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('image', models.ImageField(upload_to='', verbose_name='Product image')),
                ('description', models.TextField(verbose_name='Product description')),
                ('height', models.IntegerField(verbose_name='Product height')),
                ('width', models.IntegerField(verbose_name='Product width')),
                ('length', models.IntegerField(verbose_name='Product length')),
                ('material', models.CharField(max_length=255, verbose_name='Product material')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('votes', models.ManyToManyField(to='store.vote')),
            ],
        ),
    ]
