# Generated by Django 4.1.1 on 2022-12-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.CreateModel(
            name='Supercategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.AddField(
            model_name='category',
            name='supercat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supercategory'),
        ),
    ]
