# Generated by Django 4.1.1 on 2022-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_abstractcategory_remove_category_supercategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
