# Generated by Django 4.1.1 on 2022-11-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_abstractcontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('abstractcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcontainer')),
                ('products', models.ManyToManyField(to='store.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcontainer',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('abstractcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcontainer')),
                ('products', models.ManyToManyField(to='store.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcontainer',),
        ),
    ]
