# Generated by Django 4.1.1 on 2022-12-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_vote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
    ]
