# Generated by Django 4.1.1 on 2022-11-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_favourite_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.CreateModel(
            name='ProductSupercategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractcategory',),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='supercategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productsupercategory'),
        ),
    ]
