# Generated by Django 4.1.1 on 2022-11-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productcategory_productsupercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='supercategory',
            field=models.ForeignKey(blank=True, default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.productsupercategory'),
        ),
    ]
